---
- name: install etcd
  yum:
    pkg: etcd
    state: installed

- name: create etcd conf
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
  notify:
    - restart etcd

- name: start etcd
  service:
    name: etcd
    enabled: yes
    state: started
